/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.AddBook;
import GUI.AddMagazines;
import GUI.AddNewpaper;
import GUI.DeleteBook;
import GUI.DeleteMagazine;
import GUI.DeleteNewpaper;
import GUI.SearchBook;
import GUI.SearchMagazine;
import GUI.SearchNewpaper;

/**
 *
 * @author TGDD
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Menu() {
        initComponents();
        SbookBtn.setVisible(false);
        SMagazineBtn.setVisible(false);
        SNewpaperBtn.setVisible(false);
        
        DBookBtn.setVisible(false);
        DMagazineBtn.setVisible(false);
        DNewpaperBtn.setVisible(false);
        
        ABookBtn.setVisible(false);
        AMagazineBtn.setVisible(false);
        ANewpaperBtn.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        SbookBtn = new javax.swing.JButton();
        SMagazineBtn = new javax.swing.JButton();
        SNewpaperBtn = new javax.swing.JButton();
        ABookBtn = new javax.swing.JButton();
        AMagazineBtn = new javax.swing.JButton();
        ANewpaperBtn = new javax.swing.JButton();
        DBookBtn = new javax.swing.JButton();
        DMagazineBtn = new javax.swing.JButton();
        DNewpaperBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("QUẢN LÝ TÀI LIỆU");
        title.setToolTipText("");

        searchBtn.setBackground(new java.awt.Color(51, 255, 51));
        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchBtn.setText("Tìm tài liệu");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn1.setBackground(new java.awt.Color(255, 255, 51));
        addBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn1.setText("Thêm tài liệu");
        addBtn1.setToolTipText("");
        addBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("Xóa tài liệu");
        deleteBtn.setToolTipText("");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        SbookBtn.setText("Sách");
        SbookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbookBtnActionPerformed(evt);
            }
        });

        SMagazineBtn.setText("Tạp Chí");
        SMagazineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMagazineBtnActionPerformed(evt);
            }
        });

        SNewpaperBtn.setText("Báo");
        SNewpaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNewpaperBtnActionPerformed(evt);
            }
        });

        ABookBtn.setText("Sách");
        ABookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABookBtnActionPerformed(evt);
            }
        });

        AMagazineBtn.setText("Tạp Chí");
        AMagazineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMagazineBtnActionPerformed(evt);
            }
        });

        ANewpaperBtn.setText("Báo");
        ANewpaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANewpaperBtnActionPerformed(evt);
            }
        });

        DBookBtn.setText("Sách");
        DBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBookBtnActionPerformed(evt);
            }
        });

        DMagazineBtn.setText("Tạp Chí");
        DMagazineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMagazineBtnActionPerformed(evt);
            }
        });

        DNewpaperBtn.setText("Báo");
        DNewpaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNewpaperBtnActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(255, 0, 0));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeBtn.setText("Đóng");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SbookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(SMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(SNewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ABookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(AMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ANewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(DBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(DMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DNewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SbookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ABookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMagazineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNewpaperBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SbookBtn.setVisible(true);
        SMagazineBtn.setVisible(true);
        SNewpaperBtn.setVisible(true);
        
        DBookBtn.setVisible(false);
        DMagazineBtn.setVisible(false);
        DNewpaperBtn.setVisible(false);
        
        ABookBtn.setVisible(false);
        AMagazineBtn.setVisible(false);
        ANewpaperBtn.setVisible(false);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
        ABookBtn.setVisible(true);
        AMagazineBtn.setVisible(true);
        ANewpaperBtn.setVisible(true);
        
        SbookBtn.setVisible(false);
        SMagazineBtn.setVisible(false);
        SNewpaperBtn.setVisible(false);
        
        DBookBtn.setVisible(false);
        DMagazineBtn.setVisible(false);
        DNewpaperBtn.setVisible(false);
        
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        DBookBtn.setVisible(true);
        DMagazineBtn.setVisible(true);
        DNewpaperBtn.setVisible(true);
        
        ABookBtn.setVisible(false);
        AMagazineBtn.setVisible(false);
        ANewpaperBtn.setVisible(false);
        
        SbookBtn.setVisible(false);
        SMagazineBtn.setVisible(false);
        SNewpaperBtn.setVisible(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void SMagazineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMagazineBtnActionPerformed
        // TODO add your handling code here:
        new SearchMagazine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SMagazineBtnActionPerformed

    private void AMagazineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMagazineBtnActionPerformed
        // TODO add your handling code here:
        new AddMagazines().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AMagazineBtnActionPerformed

    private void DMagazineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMagazineBtnActionPerformed
        // TODO add your handling code here:
        new DeleteMagazine().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DMagazineBtnActionPerformed

    private void SbookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbookBtnActionPerformed
        new SearchBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SbookBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnActionPerformed

    private void SNewpaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNewpaperBtnActionPerformed
        // TODO add your handling code here:
        new SearchNewpaper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SNewpaperBtnActionPerformed

    private void ABookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABookBtnActionPerformed
        // TODO add your handling code here:
        new AddBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ABookBtnActionPerformed

    private void ANewpaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANewpaperBtnActionPerformed
        // TODO add your handling code here:
        new AddNewpaper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ANewpaperBtnActionPerformed

    private void DBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBookBtnActionPerformed
        // TODO add your handling code here:
        new DeleteBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DBookBtnActionPerformed

    private void DNewpaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNewpaperBtnActionPerformed
        // TODO add your handling code here:
        new DeleteNewpaper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DNewpaperBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABookBtn;
    private javax.swing.JButton AMagazineBtn;
    private javax.swing.JButton ANewpaperBtn;
    private javax.swing.JButton DBookBtn;
    private javax.swing.JButton DMagazineBtn;
    private javax.swing.JButton DNewpaperBtn;
    private javax.swing.JButton SMagazineBtn;
    private javax.swing.JButton SNewpaperBtn;
    private javax.swing.JButton SbookBtn;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
