/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Magazine;
import Services.Services;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author TGDD
 */
public class SearchMagazine extends javax.swing.JFrame {
    Services searchMagazine;
    
    /**
     * Creates new form SearchBook
     */
    public SearchMagazine() {
        initComponents();
        searchOutput.setVisible(false);
        jLabel1.setVisible(false);
        MagCodeTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchMagTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MagCodeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        searchOutput = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        getAllmgzBtn = new javax.swing.JButton();
        getWithCodeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchMagTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        searchMagTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchMagTitle.setText("Tìm Tạp Chí");

        jLabel1.setText("Nhập mã tạp chí:");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(resultTable);

        searchOutput.setText("Kết quả");
        searchOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOutputActionPerformed(evt);
            }
        });

        backBtn.setText("Quay lại");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        getAllmgzBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getAllmgzBtn.setText("Hiển thị tất cả tạp chí");
        getAllmgzBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllmgzBtnActionPerformed(evt);
            }
        });

        getWithCodeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getWithCodeBtn.setText("Tìm theo mã tạp chí");
        getWithCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getWithCodeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchMagTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MagCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getAllmgzBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(getWithCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(searchMagTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAllmgzBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getWithCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MagCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOutputActionPerformed
        searchMagazine = new Services();
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        resultTable.setModel(defaultTableModel);
        
        
        defaultTableModel.addColumn("Mã Tạp Chí");
        defaultTableModel.addColumn("Nhà Xuất Bản");
        defaultTableModel.addColumn("Số Bản Phát Hành ");
        defaultTableModel.addColumn("Số Phát Hành");
        defaultTableModel.addColumn("Tháng Phát Hành");
        
        List<Magazine> magazines = searchMagazine.getMagazine(MagCodeTextField.getText());
        for (Magazine magazine: magazines) {
            defaultTableModel.addRow(new Object[] {
            magazine.getMgzCode(),
            magazine.getPublisher(),
            magazine.getQuantity(),
            magazine.getNumber(),
            magazine.getPublishMonth()
            });
        }
    }//GEN-LAST:event_searchOutputActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void getAllmgzBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllmgzBtnActionPerformed

        searchMagazine = new Services();

        DefaultTableModel defaultTableModel = new DefaultTableModel();
        resultTable.setModel(defaultTableModel);

        defaultTableModel.addColumn("Mã Tạp Chí");
        defaultTableModel.addColumn("Nhà Xuất Bản");
        defaultTableModel.addColumn("Số Bản Phát Hành ");
        defaultTableModel.addColumn("Số Phát Hành");
        defaultTableModel.addColumn("Tháng Phát Hành");

        List<Magazine> magazines = searchMagazine.getALlMagazines(MagCodeTextField.getText());
        for (Magazine magazine: magazines) {
            defaultTableModel.addRow(new Object[] {
                magazine.getMgzCode(),
                magazine.getPublisher(),
                magazine.getQuantity(),
                magazine.getNumber(),
                magazine.getPublishMonth()
            });
        }        // TODO add your handling code here:
    }//GEN-LAST:event_getAllmgzBtnActionPerformed

    private void getWithCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getWithCodeBtnActionPerformed
        // TODO add your handling code here:
        searchOutput.setVisible(true);
        jLabel1.setVisible(true);
        MagCodeTextField.setVisible(true);
    }//GEN-LAST:event_getWithCodeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MagCodeTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton getAllmgzBtn;
    private javax.swing.JButton getWithCodeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private javax.swing.JLabel searchMagTitle;
    private javax.swing.JButton searchOutput;
    // End of variables declaration//GEN-END:variables
}
