/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Book;
import Services.Services;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author TGDD
 */
public class SearchBook extends javax.swing.JFrame {
    Services searchBook;

    /**
     * Creates new form SearchBook
     */
    public SearchBook() {
        initComponents();
        searchOutput.setVisible(false);
        jLabel1.setVisible(false);
        bookCodeTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBookTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bookCodeTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        searchOutput = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        getAllBookBtn = new javax.swing.JButton();
        getWithCodeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchBookTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        searchBookTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBookTitle.setText("Tìm Sách");

        jLabel1.setText("Nhập mã sách:");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(resultTable);

        searchOutput.setText("Kết quả");
        searchOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOutputActionPerformed(evt);
            }
        });

        backBtn.setText("Quay lại");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        getAllBookBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getAllBookBtn.setText("Hiển thị tất cả sách");
        getAllBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllBookBtnActionPerformed(evt);
            }
        });

        getWithCodeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getWithCodeBtn.setText("Tìm theo mã sách");
        getWithCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getWithCodeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBookTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bookCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(getAllBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(getWithCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(searchBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAllBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getWithCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOutputActionPerformed
        searchBook = new Services();
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        resultTable.setModel(defaultTableModel);
        
        
        defaultTableModel.addColumn("Mã Sách");
        defaultTableModel.addColumn("Tên Sách");
        defaultTableModel.addColumn("Nhà Xuất Bản");
        defaultTableModel.addColumn("Tác Giả");
        defaultTableModel.addColumn("Số Bản Phát Hành ");
        defaultTableModel.addColumn("Số Trang");
        
        List<Book> Books = searchBook.getBook(bookCodeTextField.getText());
        for (Book book: Books) {
            defaultTableModel.addRow(new Object[] {
            book.getBookCode(),
            book.getBookName(),
            book.getPublisher(),
            book.getAuthor(),
            book.getQuantity(),
            book.getPageNum()
            });
        }
    }//GEN-LAST:event_searchOutputActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void getAllBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllBookBtnActionPerformed

        searchBook = new Services();
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        resultTable.setModel(defaultTableModel);
        
        
        defaultTableModel.addColumn("Mã Sách");
        defaultTableModel.addColumn("Tên Sách");
        defaultTableModel.addColumn("Nhà Xuất Bản");
        defaultTableModel.addColumn("Tác Giả");
        defaultTableModel.addColumn("Số Bản Phát Hành ");
        defaultTableModel.addColumn("Số Trang");
        
        List<Book> Books = searchBook.getAllBooks(bookCodeTextField.getText());
        for (Book book: Books) {
            defaultTableModel.addRow(new Object[] {
            book.getBookCode(),
            book.getBookName(),
            book.getPublisher(),
            book.getAuthor(),
            book.getQuantity(),
            book.getPageNum()
            });
        }        // TODO add your handling code here:
    }//GEN-LAST:event_getAllBookBtnActionPerformed

    private void getWithCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getWithCodeBtnActionPerformed
        // TODO add your handling code here:
        searchOutput.setVisible(true);
        jLabel1.setVisible(true);
        bookCodeTextField.setVisible(true);
    }//GEN-LAST:event_getWithCodeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bookCodeTextField;
    private javax.swing.JButton getAllBookBtn;
    private javax.swing.JButton getWithCodeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resultTable;
    private javax.swing.JLabel searchBookTitle;
    private javax.swing.JButton searchOutput;
    // End of variables declaration//GEN-END:variables
}
